require("plugins.colorscheme")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.harpoon")
require("plugins.undotree")
require("plugins.fugitive")
require("plugins.lsp")
require("plugins.ibl")
require("plugins.conform")
-- require("plugins.netrw")
require("plugins.autopairs")
require("plugins.noice")
require("plugins.obsidian")
require("plugins.commander")
require("plugins.oil")
require("plugins.lualine")

-- require("plugins.lualine")
-- require("plugins.neotree")
